
// This file has been generated by the GUI designer. Do not modify.

public partial class CharacterWindow
{
	private global::Gtk.VBox vbox5;
	private global::Gtk.HBox Character_Pane;
	private global::Gtk.VBox vbox9;
	private global::Gtk.Frame Attributes_Frame;
	private global::Gtk.Alignment GtkAlignment2;
	private global::Gtk.VBox Attribute_Vbox;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Label CharacterName_Label;
	private global::Gtk.Entry Name_Textbox;
	private global::Gtk.CheckButton Bot_Checkbox;
	private global::Gtk.HSeparator hseparator2;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label Body_Label;
	private global::Gtk.Entry Body_Textbox;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label Agility_Label;
	private global::Gtk.Entry Agility_Textbox;
	private global::Gtk.HBox hbox12;
	private global::Gtk.Label Strength_Label;
	private global::Gtk.Entry Strength_Textbox;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Label Reaction_Label;
	private global::Gtk.Entry Reaction_Textbox;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label Willpower_Label;
	private global::Gtk.Entry Willpower_Textbox;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label Logic_Label;
	private global::Gtk.Entry Logic_Textbox;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Label Intuiton_Label;
	private global::Gtk.Entry Intuition_Textbox;
	private global::Gtk.HBox hbox8;
	private global::Gtk.Label Charisma_Label;
	private global::Gtk.Entry Charisma_Textbox;
	private global::Gtk.HSeparator hseparator5;
	private global::Gtk.HBox hbox54;
	private global::Gtk.Label Initiative_Label;
	private global::Gtk.Entry InitiativeDiceCount_Textbox;
	private global::Gtk.Label InitiativeModifier_Label;
	private global::Gtk.Entry InitiativeModifier_Textbox;
	private global::Gtk.HSeparator hseparator1;
	private global::Gtk.HBox hbox51;
	private global::Gtk.Label Armor_Label;
	private global::Gtk.Entry Armor_Textbox;
	private global::Gtk.Label AttributesFrame_Label;
	private global::Gtk.Frame Skills_Frame;
	private global::Gtk.Alignment GtkAlignment3;
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox13;
	private global::Gtk.Label Archery_Label;
	private global::Gtk.SpinButton Archery_Spinbox;
	private global::Gtk.HBox hbox14;
	private global::Gtk.Label Automatics_Label;
	private global::Gtk.SpinButton AutomaticsSpinbox;
	private global::Gtk.HBox hbox15;
	private global::Gtk.Label Blades_Label;
	private global::Gtk.SpinButton Blades_Spinbox;
	private global::Gtk.HBox hbox16;
	private global::Gtk.Label Clubs_Label;
	private global::Gtk.SpinButton Clubs_Spinbox;
	private global::Gtk.HBox hbox17;
	private global::Gtk.Label HeavyWeapons_Label;
	private global::Gtk.SpinButton HeavyWeapons_Spinbox;
	private global::Gtk.HBox hbox18;
	private global::Gtk.Label Longarms_Label;
	private global::Gtk.SpinButton Longarms_Spinbox;
	private global::Gtk.HBox hbox19;
	private global::Gtk.Label Pistols_Label;
	private global::Gtk.SpinButton Pistols_Spinbox;
	private global::Gtk.HBox hbox20;
	private global::Gtk.Label ThrowingWeapons_Label;
	private global::Gtk.SpinButton ThrowingWeapons_Spinbox;
	private global::Gtk.HBox hbox;
	private global::Gtk.Label UnarmedCombat_Label;
	private global::Gtk.SpinButton UnarmedCombat_Spinbox;
	private global::Gtk.Label SkillsFrame_Label;
	private global::Gtk.Button ImportAttributeSection_Button;
	private global::Gtk.Frame Weapons_Frame;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.VBox Weapons_Vbox;
	private global::Gtk.Frame RangedWeapon_Frame;
	private global::Gtk.Alignment GtkAlignment4;
	private global::Gtk.VBox vbox7;
	private global::Gtk.Label RangedWeapon_Label;
	private global::Gtk.HBox hbox10;
	private global::Gtk.Label RangedWeaponName_Label;
	private global::Gtk.Entry RangedWeaponName_Textbox;
	private global::Gtk.HBox hbox55;
	private global::Gtk.Label RangedDamage_Label1;
	private global::Gtk.Entry RangedDamage_Textbox;
	private global::Gtk.HBox hbox59;
	private global::Gtk.Label RangedDamage_Label;
	private global::Gtk.RadioButton RangedPhysicalDamage_Radio;
	private global::Gtk.RadioButton RangedStunDamage_Radio;
	private global::Gtk.HBox hbox57;
	private global::Gtk.Label RangedAccuracy;
	private global::Gtk.Entry RangedAccuracy_Textbox;
	private global::Gtk.HBox hbox58;
	private global::Gtk.Label RangedAP_Label;
	private global::Gtk.Entry RangedWeaponAP_Textbox;
	private global::Gtk.HBox hbox11;
	private global::Gtk.Label RangedRecoil_Label;
	private global::Gtk.Entry RangedRecoil_Textbox;
	private global::Gtk.HBox hbox26;
	private global::Gtk.Label MagSize_Label;
	private global::Gtk.Entry MagSize_Textbox;
	private global::Gtk.Expander FiringModes_Expander;
	private global::Gtk.VBox vbox3;
	private global::Gtk.HBox hbox60;
	private global::Gtk.CheckButton SingleShot_Checkbox;
	private global::Gtk.CheckButton SemiAutomatic_Checkbox;
	private global::Gtk.HBox hbox61;
	private global::Gtk.CheckButton SemiAutomaticBurst_Checkbox;
	private global::Gtk.CheckButton BurstFire_Checkbox;
	private global::Gtk.HBox hbox62;
	private global::Gtk.CheckButton LongBurst_Checkbox;
	private global::Gtk.CheckButton FullAuto_Checkbox;
	private global::Gtk.Label FiringModesExpander_Label;
	private global::Gtk.Expander RangedSkill_Expander;
	private global::Gtk.VBox vbox6;
	private global::Gtk.HBox hbox21;
	private global::Gtk.RadioButton Archery_Radio;
	private global::Gtk.RadioButton Automatics_Radio;
	private global::Gtk.HBox hbox22;
	private global::Gtk.RadioButton HeavyWeapons_Radio;
	private global::Gtk.RadioButton Longarms_Radio;
	private global::Gtk.HBox hbox23;
	private global::Gtk.RadioButton ThrowingWeapons_Radio;
	private global::Gtk.RadioButton Pistols_Radio;
	private global::Gtk.Label RangedSkillExpander_Label;
	private global::Gtk.Button ImportRanged_Button;
	private global::Gtk.HSeparator hseparator4;
	private global::Gtk.Frame MeleeWeapon_Frame;
	private global::Gtk.Alignment GtkAlignment5;
	private global::Gtk.VBox vbox8;
	private global::Gtk.Label MeleeWeapon_Label;
	private global::Gtk.HBox hbox9;
	private global::Gtk.Label MeleeWeaponName_Label;
	private global::Gtk.Entry MeleeWeaponName_Textbox;
	private global::Gtk.HBox hbox63;
	private global::Gtk.Label MeleeDamage_Label;
	private global::Gtk.Entry MeleeDamage_Textbox;
	private global::Gtk.HBox hbox64;
	private global::Gtk.Label MeleeDamageType_Label;
	private global::Gtk.RadioButton MeleePhysicalDamage_Radio;
	private global::Gtk.RadioButton MeleeStunDamage_Radio;
	private global::Gtk.HBox hbox65;
	private global::Gtk.Label MeleeAP_Label;
	private global::Gtk.Entry MeleeAP_Textbox;
	private global::Gtk.HBox hbox28;
	private global::Gtk.Label MeleeAccuracy_Label;
	private global::Gtk.Entry MeleeAccuracy_Textbox;
	private global::Gtk.Expander MeleeSkill_Expander;
	private global::Gtk.VBox vbox10;
	private global::Gtk.HBox hbox25;
	private global::Gtk.RadioButton Blades_Radio;
	private global::Gtk.RadioButton Clubs_Radio;
	private global::Gtk.HBox hbox24;
	private global::Gtk.RadioButton Unarmed_Radio;
	private global::Gtk.Label MeleeSkillExpander_Label;
	private global::Gtk.Button ImportWeapons_Button;
	private global::Gtk.Label WeaponsPane_Label;
	private global::Gtk.HSeparator hseparator3;
	private global::Gtk.Button SubmitCharacter_Button;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget CharacterWindow
		this.Name = "CharacterWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Shadowrun Tool");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowShrink = true;
		// Container child CharacterWindow.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.Character_Pane = new global::Gtk.HBox ();
		this.Character_Pane.Name = "Character_Pane";
		this.Character_Pane.Homogeneous = true;
		// Container child Character_Pane.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.Attributes_Frame = new global::Gtk.Frame ();
		this.Attributes_Frame.Name = "Attributes_Frame";
		this.Attributes_Frame.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child Attributes_Frame.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.Attribute_Vbox = new global::Gtk.VBox ();
		this.Attribute_Vbox.Name = "Attribute_Vbox";
		this.Attribute_Vbox.Spacing = 6;
		// Container child Attribute_Vbox.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.CharacterName_Label = new global::Gtk.Label ();
		this.CharacterName_Label.Name = "CharacterName_Label";
		this.CharacterName_Label.Xalign = 0F;
		this.CharacterName_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
		this.hbox1.Add (this.CharacterName_Label);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.CharacterName_Label]));
		w1.Position = 0;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Name_Textbox = new global::Gtk.Entry ();
		this.Name_Textbox.CanFocus = true;
		this.Name_Textbox.Name = "Name_Textbox";
		this.Name_Textbox.IsEditable = true;
		this.Name_Textbox.InvisibleChar = '●';
		this.hbox1.Add (this.Name_Textbox);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.Name_Textbox]));
		w2.Position = 1;
		w2.Expand = false;
		this.Attribute_Vbox.Add (this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.Attribute_Vbox [this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child Attribute_Vbox.Gtk.Box+BoxChild
		this.Bot_Checkbox = new global::Gtk.CheckButton ();
		this.Bot_Checkbox.CanFocus = true;
		this.Bot_Checkbox.Name = "Bot_Checkbox";
		this.Bot_Checkbox.Label = global::Mono.Unix.Catalog.GetString ("Autonamous");
		this.Bot_Checkbox.Active = true;
		this.Bot_Checkbox.DrawIndicator = true;
		this.Bot_Checkbox.UseUnderline = true;
		this.Attribute_Vbox.Add (this.Bot_Checkbox);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.Attribute_Vbox [this.Bot_Checkbox]));
		w4.Position = 1;
		// Container child Attribute_Vbox.Gtk.Box+BoxChild
		this.hseparator2 = new global::Gtk.HSeparator ();
		this.hseparator2.Name = "hseparator2";
		this.Attribute_Vbox.Add (this.hseparator2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.Attribute_Vbox [this.hseparator2]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child Attribute_Vbox.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.Body_Label = new global::Gtk.Label ();
		this.Body_Label.Name = "Body_Label";
		this.Body_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Body");
		this.hbox2.Add (this.Body_Label);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.Body_Label]));
		w6.Position = 0;
		w6.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.Body_Textbox = new global::Gtk.Entry ();
		this.Body_Textbox.CanFocus = true;
		this.Body_Textbox.Name = "Body_Textbox";
		this.Body_Textbox.IsEditable = true;
		this.Body_Textbox.InvisibleChar = '●';
		this.hbox2.Add (this.Body_Textbox);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.Body_Textbox]));
		w7.Position = 1;
		w7.Expand = false;
		this.Attribute_Vbox.Add (this.hbox2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.Attribute_Vbox [this.hbox2]));
		w8.Position = 3;
		w8.Expand = false;
		w8.Fill = false;
		// Container child Attribute_Vbox.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.Agility_Label = new global::Gtk.Label ();
		this.Agility_Label.Name = "Agility_Label";
		this.Agility_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Agility");
		this.hbox3.Add (this.Agility_Label);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.Agility_Label]));
		w9.Position = 0;
		w9.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.Agility_Textbox = new global::Gtk.Entry ();
		this.Agility_Textbox.CanFocus = true;
		this.Agility_Textbox.Name = "Agility_Textbox";
		this.Agility_Textbox.IsEditable = true;
		this.Agility_Textbox.InvisibleChar = '●';
		this.hbox3.Add (this.Agility_Textbox);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.Agility_Textbox]));
		w10.Position = 1;
		w10.Expand = false;
		this.Attribute_Vbox.Add (this.hbox3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.Attribute_Vbox [this.hbox3]));
		w11.Position = 4;
		w11.Expand = false;
		w11.Fill = false;
		// Container child Attribute_Vbox.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.Strength_Label = new global::Gtk.Label ();
		this.Strength_Label.Name = "Strength_Label";
		this.Strength_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Strength");
		this.hbox12.Add (this.Strength_Label);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.Strength_Label]));
		w12.Position = 0;
		w12.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.Strength_Textbox = new global::Gtk.Entry ();
		this.Strength_Textbox.CanFocus = true;
		this.Strength_Textbox.Name = "Strength_Textbox";
		this.Strength_Textbox.IsEditable = true;
		this.Strength_Textbox.InvisibleChar = '●';
		this.hbox12.Add (this.Strength_Textbox);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.Strength_Textbox]));
		w13.Position = 1;
		w13.Expand = false;
		this.Attribute_Vbox.Add (this.hbox12);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.Attribute_Vbox [this.hbox12]));
		w14.Position = 5;
		w14.Expand = false;
		w14.Fill = false;
		// Container child Attribute_Vbox.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.Reaction_Label = new global::Gtk.Label ();
		this.Reaction_Label.Name = "Reaction_Label";
		this.Reaction_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Reaction");
		this.hbox4.Add (this.Reaction_Label);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.Reaction_Label]));
		w15.Position = 0;
		w15.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.Reaction_Textbox = new global::Gtk.Entry ();
		this.Reaction_Textbox.CanFocus = true;
		this.Reaction_Textbox.Name = "Reaction_Textbox";
		this.Reaction_Textbox.IsEditable = true;
		this.Reaction_Textbox.InvisibleChar = '●';
		this.hbox4.Add (this.Reaction_Textbox);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.Reaction_Textbox]));
		w16.Position = 1;
		w16.Expand = false;
		this.Attribute_Vbox.Add (this.hbox4);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.Attribute_Vbox [this.hbox4]));
		w17.Position = 6;
		w17.Expand = false;
		w17.Fill = false;
		// Container child Attribute_Vbox.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.Willpower_Label = new global::Gtk.Label ();
		this.Willpower_Label.Name = "Willpower_Label";
		this.Willpower_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Willpower");
		this.hbox5.Add (this.Willpower_Label);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.Willpower_Label]));
		w18.Position = 0;
		w18.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.Willpower_Textbox = new global::Gtk.Entry ();
		this.Willpower_Textbox.CanFocus = true;
		this.Willpower_Textbox.Name = "Willpower_Textbox";
		this.Willpower_Textbox.IsEditable = true;
		this.Willpower_Textbox.InvisibleChar = '●';
		this.hbox5.Add (this.Willpower_Textbox);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.Willpower_Textbox]));
		w19.Position = 1;
		w19.Expand = false;
		this.Attribute_Vbox.Add (this.hbox5);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.Attribute_Vbox [this.hbox5]));
		w20.Position = 7;
		w20.Expand = false;
		w20.Fill = false;
		// Container child Attribute_Vbox.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.Logic_Label = new global::Gtk.Label ();
		this.Logic_Label.Name = "Logic_Label";
		this.Logic_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Logic");
		this.hbox6.Add (this.Logic_Label);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.Logic_Label]));
		w21.Position = 0;
		w21.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.Logic_Textbox = new global::Gtk.Entry ();
		this.Logic_Textbox.CanFocus = true;
		this.Logic_Textbox.Name = "Logic_Textbox";
		this.Logic_Textbox.IsEditable = true;
		this.Logic_Textbox.InvisibleChar = '●';
		this.hbox6.Add (this.Logic_Textbox);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.Logic_Textbox]));
		w22.Position = 1;
		w22.Expand = false;
		this.Attribute_Vbox.Add (this.hbox6);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.Attribute_Vbox [this.hbox6]));
		w23.Position = 8;
		w23.Expand = false;
		w23.Fill = false;
		// Container child Attribute_Vbox.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.Intuiton_Label = new global::Gtk.Label ();
		this.Intuiton_Label.Name = "Intuiton_Label";
		this.Intuiton_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Intuition");
		this.hbox7.Add (this.Intuiton_Label);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.Intuiton_Label]));
		w24.Position = 0;
		w24.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.Intuition_Textbox = new global::Gtk.Entry ();
		this.Intuition_Textbox.CanFocus = true;
		this.Intuition_Textbox.Name = "Intuition_Textbox";
		this.Intuition_Textbox.IsEditable = true;
		this.Intuition_Textbox.InvisibleChar = '●';
		this.hbox7.Add (this.Intuition_Textbox);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.Intuition_Textbox]));
		w25.Position = 1;
		w25.Expand = false;
		this.Attribute_Vbox.Add (this.hbox7);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.Attribute_Vbox [this.hbox7]));
		w26.Position = 9;
		w26.Expand = false;
		w26.Fill = false;
		// Container child Attribute_Vbox.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.Charisma_Label = new global::Gtk.Label ();
		this.Charisma_Label.Name = "Charisma_Label";
		this.Charisma_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Charisma");
		this.hbox8.Add (this.Charisma_Label);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.Charisma_Label]));
		w27.Position = 0;
		w27.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.Charisma_Textbox = new global::Gtk.Entry ();
		this.Charisma_Textbox.CanFocus = true;
		this.Charisma_Textbox.Name = "Charisma_Textbox";
		this.Charisma_Textbox.IsEditable = true;
		this.Charisma_Textbox.InvisibleChar = '●';
		this.hbox8.Add (this.Charisma_Textbox);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.Charisma_Textbox]));
		w28.Position = 1;
		w28.Expand = false;
		this.Attribute_Vbox.Add (this.hbox8);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.Attribute_Vbox [this.hbox8]));
		w29.Position = 10;
		w29.Expand = false;
		w29.Fill = false;
		// Container child Attribute_Vbox.Gtk.Box+BoxChild
		this.hseparator5 = new global::Gtk.HSeparator ();
		this.hseparator5.Name = "hseparator5";
		this.Attribute_Vbox.Add (this.hseparator5);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.Attribute_Vbox [this.hseparator5]));
		w30.Position = 11;
		w30.Expand = false;
		w30.Fill = false;
		// Container child Attribute_Vbox.Gtk.Box+BoxChild
		this.hbox54 = new global::Gtk.HBox ();
		this.hbox54.Name = "hbox54";
		this.hbox54.Spacing = 6;
		// Container child hbox54.Gtk.Box+BoxChild
		this.Initiative_Label = new global::Gtk.Label ();
		this.Initiative_Label.Name = "Initiative_Label";
		this.Initiative_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Initiative");
		this.hbox54.Add (this.Initiative_Label);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox54 [this.Initiative_Label]));
		w31.Position = 0;
		w31.Fill = false;
		// Container child hbox54.Gtk.Box+BoxChild
		this.InitiativeDiceCount_Textbox = new global::Gtk.Entry ();
		this.InitiativeDiceCount_Textbox.WidthRequest = 35;
		this.InitiativeDiceCount_Textbox.CanFocus = true;
		this.InitiativeDiceCount_Textbox.Name = "InitiativeDiceCount_Textbox";
		this.InitiativeDiceCount_Textbox.IsEditable = true;
		this.InitiativeDiceCount_Textbox.InvisibleChar = '●';
		this.hbox54.Add (this.InitiativeDiceCount_Textbox);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox54 [this.InitiativeDiceCount_Textbox]));
		w32.Position = 1;
		// Container child hbox54.Gtk.Box+BoxChild
		this.InitiativeModifier_Label = new global::Gtk.Label ();
		this.InitiativeModifier_Label.Name = "InitiativeModifier_Label";
		this.InitiativeModifier_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("D6 +");
		this.hbox54.Add (this.InitiativeModifier_Label);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox54 [this.InitiativeModifier_Label]));
		w33.Position = 2;
		w33.Expand = false;
		w33.Fill = false;
		// Container child hbox54.Gtk.Box+BoxChild
		this.InitiativeModifier_Textbox = new global::Gtk.Entry ();
		this.InitiativeModifier_Textbox.WidthRequest = 35;
		this.InitiativeModifier_Textbox.CanFocus = true;
		this.InitiativeModifier_Textbox.Name = "InitiativeModifier_Textbox";
		this.InitiativeModifier_Textbox.IsEditable = true;
		this.InitiativeModifier_Textbox.InvisibleChar = '●';
		this.hbox54.Add (this.InitiativeModifier_Textbox);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox54 [this.InitiativeModifier_Textbox]));
		w34.Position = 3;
		this.Attribute_Vbox.Add (this.hbox54);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.Attribute_Vbox [this.hbox54]));
		w35.Position = 12;
		w35.Expand = false;
		w35.Fill = false;
		// Container child Attribute_Vbox.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.Attribute_Vbox.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.Attribute_Vbox [this.hseparator1]));
		w36.Position = 13;
		w36.Expand = false;
		w36.Fill = false;
		// Container child Attribute_Vbox.Gtk.Box+BoxChild
		this.hbox51 = new global::Gtk.HBox ();
		this.hbox51.Name = "hbox51";
		this.hbox51.Spacing = 6;
		// Container child hbox51.Gtk.Box+BoxChild
		this.Armor_Label = new global::Gtk.Label ();
		this.Armor_Label.Name = "Armor_Label";
		this.Armor_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Armor");
		this.hbox51.Add (this.Armor_Label);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox51 [this.Armor_Label]));
		w37.Position = 0;
		w37.Fill = false;
		// Container child hbox51.Gtk.Box+BoxChild
		this.Armor_Textbox = new global::Gtk.Entry ();
		this.Armor_Textbox.CanFocus = true;
		this.Armor_Textbox.Name = "Armor_Textbox";
		this.Armor_Textbox.IsEditable = true;
		this.Armor_Textbox.InvisibleChar = '●';
		this.hbox51.Add (this.Armor_Textbox);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox51 [this.Armor_Textbox]));
		w38.Position = 1;
		w38.Expand = false;
		this.Attribute_Vbox.Add (this.hbox51);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.Attribute_Vbox [this.hbox51]));
		w39.Position = 14;
		w39.Expand = false;
		w39.Fill = false;
		this.GtkAlignment2.Add (this.Attribute_Vbox);
		this.Attributes_Frame.Add (this.GtkAlignment2);
		this.AttributesFrame_Label = new global::Gtk.Label ();
		this.AttributesFrame_Label.Name = "AttributesFrame_Label";
		this.AttributesFrame_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Attributes</b>");
		this.AttributesFrame_Label.UseMarkup = true;
		this.Attributes_Frame.LabelWidget = this.AttributesFrame_Label;
		this.vbox9.Add (this.Attributes_Frame);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.Attributes_Frame]));
		w42.Position = 0;
		w42.Expand = false;
		w42.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.Skills_Frame = new global::Gtk.Frame ();
		this.Skills_Frame.Name = "Skills_Frame";
		this.Skills_Frame.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child Skills_Frame.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.Archery_Label = new global::Gtk.Label ();
		this.Archery_Label.Name = "Archery_Label";
		this.Archery_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Archery");
		this.hbox13.Add (this.Archery_Label);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.Archery_Label]));
		w43.Position = 0;
		w43.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.Archery_Spinbox = new global::Gtk.SpinButton (0, 100, 1);
		this.Archery_Spinbox.CanFocus = true;
		this.Archery_Spinbox.Name = "Archery_Spinbox";
		this.Archery_Spinbox.Adjustment.PageIncrement = 10;
		this.Archery_Spinbox.ClimbRate = 1;
		this.Archery_Spinbox.Numeric = true;
		this.hbox13.Add (this.Archery_Spinbox);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.Archery_Spinbox]));
		w44.Position = 1;
		w44.Expand = false;
		w44.Fill = false;
		this.vbox2.Add (this.hbox13);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox13]));
		w45.Position = 0;
		w45.Expand = false;
		w45.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox ();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.Automatics_Label = new global::Gtk.Label ();
		this.Automatics_Label.Name = "Automatics_Label";
		this.Automatics_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Automatics");
		this.hbox14.Add (this.Automatics_Label);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.Automatics_Label]));
		w46.Position = 0;
		w46.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.AutomaticsSpinbox = new global::Gtk.SpinButton (0, 100, 1);
		this.AutomaticsSpinbox.CanFocus = true;
		this.AutomaticsSpinbox.Name = "AutomaticsSpinbox";
		this.AutomaticsSpinbox.Adjustment.PageIncrement = 10;
		this.AutomaticsSpinbox.ClimbRate = 1;
		this.AutomaticsSpinbox.Numeric = true;
		this.hbox14.Add (this.AutomaticsSpinbox);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.AutomaticsSpinbox]));
		w47.Position = 1;
		w47.Expand = false;
		w47.Fill = false;
		this.vbox2.Add (this.hbox14);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox14]));
		w48.Position = 1;
		w48.Expand = false;
		w48.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox15 = new global::Gtk.HBox ();
		this.hbox15.Name = "hbox15";
		this.hbox15.Spacing = 6;
		// Container child hbox15.Gtk.Box+BoxChild
		this.Blades_Label = new global::Gtk.Label ();
		this.Blades_Label.Name = "Blades_Label";
		this.Blades_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Blades");
		this.hbox15.Add (this.Blades_Label);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.Blades_Label]));
		w49.Position = 0;
		w49.Fill = false;
		// Container child hbox15.Gtk.Box+BoxChild
		this.Blades_Spinbox = new global::Gtk.SpinButton (0, 100, 1);
		this.Blades_Spinbox.CanFocus = true;
		this.Blades_Spinbox.Name = "Blades_Spinbox";
		this.Blades_Spinbox.Adjustment.PageIncrement = 10;
		this.Blades_Spinbox.ClimbRate = 1;
		this.Blades_Spinbox.Numeric = true;
		this.hbox15.Add (this.Blades_Spinbox);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.Blades_Spinbox]));
		w50.Position = 1;
		w50.Expand = false;
		w50.Fill = false;
		this.vbox2.Add (this.hbox15);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox15]));
		w51.Position = 2;
		w51.Expand = false;
		w51.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox16 = new global::Gtk.HBox ();
		this.hbox16.Name = "hbox16";
		this.hbox16.Spacing = 6;
		// Container child hbox16.Gtk.Box+BoxChild
		this.Clubs_Label = new global::Gtk.Label ();
		this.Clubs_Label.Name = "Clubs_Label";
		this.Clubs_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Clubs");
		this.hbox16.Add (this.Clubs_Label);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.Clubs_Label]));
		w52.Position = 0;
		w52.Fill = false;
		// Container child hbox16.Gtk.Box+BoxChild
		this.Clubs_Spinbox = new global::Gtk.SpinButton (0, 100, 1);
		this.Clubs_Spinbox.CanFocus = true;
		this.Clubs_Spinbox.Name = "Clubs_Spinbox";
		this.Clubs_Spinbox.Adjustment.PageIncrement = 10;
		this.Clubs_Spinbox.ClimbRate = 1;
		this.Clubs_Spinbox.Numeric = true;
		this.hbox16.Add (this.Clubs_Spinbox);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.Clubs_Spinbox]));
		w53.Position = 1;
		w53.Expand = false;
		w53.Fill = false;
		this.vbox2.Add (this.hbox16);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox16]));
		w54.Position = 3;
		w54.Expand = false;
		w54.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox17 = new global::Gtk.HBox ();
		this.hbox17.Name = "hbox17";
		this.hbox17.Spacing = 6;
		// Container child hbox17.Gtk.Box+BoxChild
		this.HeavyWeapons_Label = new global::Gtk.Label ();
		this.HeavyWeapons_Label.Name = "HeavyWeapons_Label";
		this.HeavyWeapons_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Heavy Weapons");
		this.hbox17.Add (this.HeavyWeapons_Label);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.HeavyWeapons_Label]));
		w55.Position = 0;
		w55.Fill = false;
		// Container child hbox17.Gtk.Box+BoxChild
		this.HeavyWeapons_Spinbox = new global::Gtk.SpinButton (0, 100, 1);
		this.HeavyWeapons_Spinbox.CanFocus = true;
		this.HeavyWeapons_Spinbox.Name = "HeavyWeapons_Spinbox";
		this.HeavyWeapons_Spinbox.Adjustment.PageIncrement = 10;
		this.HeavyWeapons_Spinbox.ClimbRate = 1;
		this.HeavyWeapons_Spinbox.Numeric = true;
		this.hbox17.Add (this.HeavyWeapons_Spinbox);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.HeavyWeapons_Spinbox]));
		w56.Position = 1;
		w56.Expand = false;
		w56.Fill = false;
		this.vbox2.Add (this.hbox17);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox17]));
		w57.Position = 4;
		w57.Expand = false;
		w57.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox18 = new global::Gtk.HBox ();
		this.hbox18.Name = "hbox18";
		this.hbox18.Spacing = 6;
		// Container child hbox18.Gtk.Box+BoxChild
		this.Longarms_Label = new global::Gtk.Label ();
		this.Longarms_Label.Name = "Longarms_Label";
		this.Longarms_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Longarms");
		this.hbox18.Add (this.Longarms_Label);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.Longarms_Label]));
		w58.Position = 0;
		w58.Fill = false;
		// Container child hbox18.Gtk.Box+BoxChild
		this.Longarms_Spinbox = new global::Gtk.SpinButton (0, 100, 1);
		this.Longarms_Spinbox.CanFocus = true;
		this.Longarms_Spinbox.Name = "Longarms_Spinbox";
		this.Longarms_Spinbox.Adjustment.PageIncrement = 10;
		this.Longarms_Spinbox.ClimbRate = 1;
		this.Longarms_Spinbox.Numeric = true;
		this.hbox18.Add (this.Longarms_Spinbox);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.Longarms_Spinbox]));
		w59.Position = 1;
		w59.Expand = false;
		w59.Fill = false;
		this.vbox2.Add (this.hbox18);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox18]));
		w60.Position = 5;
		w60.Expand = false;
		w60.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox19 = new global::Gtk.HBox ();
		this.hbox19.Name = "hbox19";
		this.hbox19.Spacing = 6;
		// Container child hbox19.Gtk.Box+BoxChild
		this.Pistols_Label = new global::Gtk.Label ();
		this.Pistols_Label.Name = "Pistols_Label";
		this.Pistols_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Pistols");
		this.hbox19.Add (this.Pistols_Label);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.Pistols_Label]));
		w61.Position = 0;
		w61.Fill = false;
		// Container child hbox19.Gtk.Box+BoxChild
		this.Pistols_Spinbox = new global::Gtk.SpinButton (0, 100, 1);
		this.Pistols_Spinbox.CanFocus = true;
		this.Pistols_Spinbox.Name = "Pistols_Spinbox";
		this.Pistols_Spinbox.Adjustment.PageIncrement = 10;
		this.Pistols_Spinbox.ClimbRate = 1;
		this.Pistols_Spinbox.Numeric = true;
		this.hbox19.Add (this.Pistols_Spinbox);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.Pistols_Spinbox]));
		w62.Position = 1;
		w62.Expand = false;
		w62.Fill = false;
		this.vbox2.Add (this.hbox19);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox19]));
		w63.Position = 6;
		w63.Expand = false;
		w63.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox20 = new global::Gtk.HBox ();
		this.hbox20.Name = "hbox20";
		this.hbox20.Spacing = 6;
		// Container child hbox20.Gtk.Box+BoxChild
		this.ThrowingWeapons_Label = new global::Gtk.Label ();
		this.ThrowingWeapons_Label.Name = "ThrowingWeapons_Label";
		this.ThrowingWeapons_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Throwing Weapons");
		this.hbox20.Add (this.ThrowingWeapons_Label);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.ThrowingWeapons_Label]));
		w64.Position = 0;
		w64.Fill = false;
		// Container child hbox20.Gtk.Box+BoxChild
		this.ThrowingWeapons_Spinbox = new global::Gtk.SpinButton (0, 100, 1);
		this.ThrowingWeapons_Spinbox.CanFocus = true;
		this.ThrowingWeapons_Spinbox.Name = "ThrowingWeapons_Spinbox";
		this.ThrowingWeapons_Spinbox.Adjustment.PageIncrement = 10;
		this.ThrowingWeapons_Spinbox.ClimbRate = 1;
		this.ThrowingWeapons_Spinbox.Numeric = true;
		this.hbox20.Add (this.ThrowingWeapons_Spinbox);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.ThrowingWeapons_Spinbox]));
		w65.Position = 1;
		w65.Expand = false;
		w65.Fill = false;
		this.vbox2.Add (this.hbox20);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox20]));
		w66.Position = 7;
		w66.Expand = false;
		w66.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox = new global::Gtk.HBox ();
		this.hbox.Name = "hbox";
		this.hbox.Spacing = 6;
		// Container child hbox.Gtk.Box+BoxChild
		this.UnarmedCombat_Label = new global::Gtk.Label ();
		this.UnarmedCombat_Label.Name = "UnarmedCombat_Label";
		this.UnarmedCombat_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Unarmed Combat");
		this.hbox.Add (this.UnarmedCombat_Label);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox [this.UnarmedCombat_Label]));
		w67.Position = 0;
		w67.Fill = false;
		// Container child hbox.Gtk.Box+BoxChild
		this.UnarmedCombat_Spinbox = new global::Gtk.SpinButton (0, 100, 1);
		this.UnarmedCombat_Spinbox.CanFocus = true;
		this.UnarmedCombat_Spinbox.Name = "UnarmedCombat_Spinbox";
		this.UnarmedCombat_Spinbox.Adjustment.PageIncrement = 10;
		this.UnarmedCombat_Spinbox.ClimbRate = 1;
		this.UnarmedCombat_Spinbox.Numeric = true;
		this.hbox.Add (this.UnarmedCombat_Spinbox);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox [this.UnarmedCombat_Spinbox]));
		w68.Position = 1;
		w68.Expand = false;
		w68.Fill = false;
		this.vbox2.Add (this.hbox);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox]));
		w69.Position = 8;
		w69.Expand = false;
		w69.Fill = false;
		this.GtkAlignment3.Add (this.vbox2);
		this.Skills_Frame.Add (this.GtkAlignment3);
		this.SkillsFrame_Label = new global::Gtk.Label ();
		this.SkillsFrame_Label.Name = "SkillsFrame_Label";
		this.SkillsFrame_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Combat Skills</b>");
		this.SkillsFrame_Label.UseMarkup = true;
		this.Skills_Frame.LabelWidget = this.SkillsFrame_Label;
		this.vbox9.Add (this.Skills_Frame);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.Skills_Frame]));
		w72.Position = 1;
		w72.Expand = false;
		w72.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.ImportAttributeSection_Button = new global::Gtk.Button ();
		this.ImportAttributeSection_Button.CanFocus = true;
		this.ImportAttributeSection_Button.Name = "ImportAttributeSection_Button";
		this.ImportAttributeSection_Button.UseUnderline = true;
		this.ImportAttributeSection_Button.Label = global::Mono.Unix.Catalog.GetString ("Import Attributes And Skills");
		this.vbox9.Add (this.ImportAttributeSection_Button);
		global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.ImportAttributeSection_Button]));
		w73.Position = 2;
		w73.Expand = false;
		w73.Fill = false;
		this.Character_Pane.Add (this.vbox9);
		global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.Character_Pane [this.vbox9]));
		w74.Position = 0;
		w74.Expand = false;
		w74.Fill = false;
		// Container child Character_Pane.Gtk.Box+BoxChild
		this.Weapons_Frame = new global::Gtk.Frame ();
		this.Weapons_Frame.Name = "Weapons_Frame";
		this.Weapons_Frame.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child Weapons_Frame.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.Weapons_Vbox = new global::Gtk.VBox ();
		this.Weapons_Vbox.Name = "Weapons_Vbox";
		this.Weapons_Vbox.Spacing = 6;
		// Container child Weapons_Vbox.Gtk.Box+BoxChild
		this.RangedWeapon_Frame = new global::Gtk.Frame ();
		this.RangedWeapon_Frame.Name = "RangedWeapon_Frame";
		this.RangedWeapon_Frame.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child RangedWeapon_Frame.Gtk.Container+ContainerChild
		this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment4.Name = "GtkAlignment4";
		this.GtkAlignment4.LeftPadding = ((uint)(12));
		// Container child GtkAlignment4.Gtk.Container+ContainerChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.RangedWeapon_Label = new global::Gtk.Label ();
		this.RangedWeapon_Label.Name = "RangedWeapon_Label";
		this.RangedWeapon_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Ranged Weapon</b>");
		this.RangedWeapon_Label.UseMarkup = true;
		this.vbox7.Add (this.RangedWeapon_Label);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.RangedWeapon_Label]));
		w75.Position = 0;
		w75.Expand = false;
		w75.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.RangedWeaponName_Label = new global::Gtk.Label ();
		this.RangedWeaponName_Label.Name = "RangedWeaponName_Label";
		this.RangedWeaponName_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
		this.hbox10.Add (this.RangedWeaponName_Label);
		global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.RangedWeaponName_Label]));
		w76.Position = 0;
		w76.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.RangedWeaponName_Textbox = new global::Gtk.Entry ();
		this.RangedWeaponName_Textbox.CanFocus = true;
		this.RangedWeaponName_Textbox.Name = "RangedWeaponName_Textbox";
		this.RangedWeaponName_Textbox.IsEditable = true;
		this.RangedWeaponName_Textbox.InvisibleChar = '●';
		this.hbox10.Add (this.RangedWeaponName_Textbox);
		global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.RangedWeaponName_Textbox]));
		w77.Position = 1;
		w77.Expand = false;
		this.vbox7.Add (this.hbox10);
		global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox10]));
		w78.Position = 1;
		w78.Expand = false;
		w78.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox55 = new global::Gtk.HBox ();
		this.hbox55.Name = "hbox55";
		this.hbox55.Spacing = 6;
		// Container child hbox55.Gtk.Box+BoxChild
		this.RangedDamage_Label1 = new global::Gtk.Label ();
		this.RangedDamage_Label1.Name = "RangedDamage_Label1";
		this.RangedDamage_Label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Damage");
		this.hbox55.Add (this.RangedDamage_Label1);
		global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.hbox55 [this.RangedDamage_Label1]));
		w79.Position = 0;
		w79.Fill = false;
		// Container child hbox55.Gtk.Box+BoxChild
		this.RangedDamage_Textbox = new global::Gtk.Entry ();
		this.RangedDamage_Textbox.CanFocus = true;
		this.RangedDamage_Textbox.Name = "RangedDamage_Textbox";
		this.RangedDamage_Textbox.IsEditable = true;
		this.RangedDamage_Textbox.InvisibleChar = '●';
		this.hbox55.Add (this.RangedDamage_Textbox);
		global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox55 [this.RangedDamage_Textbox]));
		w80.Position = 1;
		w80.Expand = false;
		this.vbox7.Add (this.hbox55);
		global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox55]));
		w81.Position = 2;
		w81.Expand = false;
		w81.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox59 = new global::Gtk.HBox ();
		this.hbox59.Name = "hbox59";
		this.hbox59.Spacing = 6;
		// Container child hbox59.Gtk.Box+BoxChild
		this.RangedDamage_Label = new global::Gtk.Label ();
		this.RangedDamage_Label.Name = "RangedDamage_Label";
		this.RangedDamage_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Type");
		this.hbox59.Add (this.RangedDamage_Label);
		global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.hbox59 [this.RangedDamage_Label]));
		w82.Position = 0;
		w82.Fill = false;
		// Container child hbox59.Gtk.Box+BoxChild
		this.RangedPhysicalDamage_Radio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Physical"));
		this.RangedPhysicalDamage_Radio.CanFocus = true;
		this.RangedPhysicalDamage_Radio.Name = "RangedPhysicalDamage_Radio";
		this.RangedPhysicalDamage_Radio.Active = true;
		this.RangedPhysicalDamage_Radio.DrawIndicator = true;
		this.RangedPhysicalDamage_Radio.UseUnderline = true;
		this.RangedPhysicalDamage_Radio.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.hbox59.Add (this.RangedPhysicalDamage_Radio);
		global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.hbox59 [this.RangedPhysicalDamage_Radio]));
		w83.Position = 1;
		w83.Expand = false;
		// Container child hbox59.Gtk.Box+BoxChild
		this.RangedStunDamage_Radio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Stun"));
		this.RangedStunDamage_Radio.CanFocus = true;
		this.RangedStunDamage_Radio.Name = "RangedStunDamage_Radio";
		this.RangedStunDamage_Radio.DrawIndicator = true;
		this.RangedStunDamage_Radio.UseUnderline = true;
		this.RangedStunDamage_Radio.Group = this.RangedPhysicalDamage_Radio.Group;
		this.hbox59.Add (this.RangedStunDamage_Radio);
		global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.hbox59 [this.RangedStunDamage_Radio]));
		w84.Position = 2;
		w84.Expand = false;
		this.vbox7.Add (this.hbox59);
		global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox59]));
		w85.Position = 3;
		w85.Expand = false;
		w85.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox57 = new global::Gtk.HBox ();
		this.hbox57.Name = "hbox57";
		this.hbox57.Spacing = 6;
		// Container child hbox57.Gtk.Box+BoxChild
		this.RangedAccuracy = new global::Gtk.Label ();
		this.RangedAccuracy.Name = "RangedAccuracy";
		this.RangedAccuracy.LabelProp = global::Mono.Unix.Catalog.GetString ("Accuracy");
		this.hbox57.Add (this.RangedAccuracy);
		global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.hbox57 [this.RangedAccuracy]));
		w86.Position = 0;
		w86.Fill = false;
		// Container child hbox57.Gtk.Box+BoxChild
		this.RangedAccuracy_Textbox = new global::Gtk.Entry ();
		this.RangedAccuracy_Textbox.CanFocus = true;
		this.RangedAccuracy_Textbox.Name = "RangedAccuracy_Textbox";
		this.RangedAccuracy_Textbox.IsEditable = true;
		this.RangedAccuracy_Textbox.InvisibleChar = '●';
		this.hbox57.Add (this.RangedAccuracy_Textbox);
		global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.hbox57 [this.RangedAccuracy_Textbox]));
		w87.Position = 1;
		w87.Expand = false;
		this.vbox7.Add (this.hbox57);
		global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox57]));
		w88.Position = 4;
		w88.Expand = false;
		w88.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox58 = new global::Gtk.HBox ();
		this.hbox58.Name = "hbox58";
		this.hbox58.Spacing = 6;
		// Container child hbox58.Gtk.Box+BoxChild
		this.RangedAP_Label = new global::Gtk.Label ();
		this.RangedAP_Label.Name = "RangedAP_Label";
		this.RangedAP_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("AP");
		this.hbox58.Add (this.RangedAP_Label);
		global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox58 [this.RangedAP_Label]));
		w89.Position = 0;
		w89.Fill = false;
		// Container child hbox58.Gtk.Box+BoxChild
		this.RangedWeaponAP_Textbox = new global::Gtk.Entry ();
		this.RangedWeaponAP_Textbox.CanFocus = true;
		this.RangedWeaponAP_Textbox.Name = "RangedWeaponAP_Textbox";
		this.RangedWeaponAP_Textbox.IsEditable = true;
		this.RangedWeaponAP_Textbox.InvisibleChar = '●';
		this.hbox58.Add (this.RangedWeaponAP_Textbox);
		global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.hbox58 [this.RangedWeaponAP_Textbox]));
		w90.Position = 1;
		w90.Expand = false;
		this.vbox7.Add (this.hbox58);
		global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox58]));
		w91.Position = 5;
		w91.Expand = false;
		w91.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.RangedRecoil_Label = new global::Gtk.Label ();
		this.RangedRecoil_Label.Name = "RangedRecoil_Label";
		this.RangedRecoil_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Recoil");
		this.hbox11.Add (this.RangedRecoil_Label);
		global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.RangedRecoil_Label]));
		w92.Position = 0;
		w92.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.RangedRecoil_Textbox = new global::Gtk.Entry ();
		this.RangedRecoil_Textbox.CanFocus = true;
		this.RangedRecoil_Textbox.Name = "RangedRecoil_Textbox";
		this.RangedRecoil_Textbox.IsEditable = true;
		this.RangedRecoil_Textbox.InvisibleChar = '●';
		this.hbox11.Add (this.RangedRecoil_Textbox);
		global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.RangedRecoil_Textbox]));
		w93.Position = 1;
		w93.Expand = false;
		this.vbox7.Add (this.hbox11);
		global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox11]));
		w94.Position = 6;
		w94.Expand = false;
		w94.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox26 = new global::Gtk.HBox ();
		this.hbox26.Name = "hbox26";
		this.hbox26.Spacing = 6;
		// Container child hbox26.Gtk.Box+BoxChild
		this.MagSize_Label = new global::Gtk.Label ();
		this.MagSize_Label.Name = "MagSize_Label";
		this.MagSize_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Magazine Size");
		this.hbox26.Add (this.MagSize_Label);
		global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.MagSize_Label]));
		w95.Position = 0;
		w95.Fill = false;
		// Container child hbox26.Gtk.Box+BoxChild
		this.MagSize_Textbox = new global::Gtk.Entry ();
		this.MagSize_Textbox.CanFocus = true;
		this.MagSize_Textbox.Name = "MagSize_Textbox";
		this.MagSize_Textbox.IsEditable = true;
		this.MagSize_Textbox.InvisibleChar = '●';
		this.hbox26.Add (this.MagSize_Textbox);
		global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.MagSize_Textbox]));
		w96.Position = 1;
		w96.Expand = false;
		this.vbox7.Add (this.hbox26);
		global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox26]));
		w97.Position = 7;
		w97.Expand = false;
		w97.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.FiringModes_Expander = new global::Gtk.Expander (null);
		this.FiringModes_Expander.CanFocus = true;
		this.FiringModes_Expander.Name = "FiringModes_Expander";
		this.FiringModes_Expander.Expanded = true;
		// Container child FiringModes_Expander.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox60 = new global::Gtk.HBox ();
		this.hbox60.Name = "hbox60";
		this.hbox60.Spacing = 6;
		// Container child hbox60.Gtk.Box+BoxChild
		this.SingleShot_Checkbox = new global::Gtk.CheckButton ();
		this.SingleShot_Checkbox.CanFocus = true;
		this.SingleShot_Checkbox.Name = "SingleShot_Checkbox";
		this.SingleShot_Checkbox.Label = global::Mono.Unix.Catalog.GetString ("Single-Shot");
		this.SingleShot_Checkbox.DrawIndicator = true;
		this.SingleShot_Checkbox.UseUnderline = true;
		this.hbox60.Add (this.SingleShot_Checkbox);
		global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.hbox60 [this.SingleShot_Checkbox]));
		w98.Position = 0;
		// Container child hbox60.Gtk.Box+BoxChild
		this.SemiAutomatic_Checkbox = new global::Gtk.CheckButton ();
		this.SemiAutomatic_Checkbox.CanFocus = true;
		this.SemiAutomatic_Checkbox.Name = "SemiAutomatic_Checkbox";
		this.SemiAutomatic_Checkbox.Label = global::Mono.Unix.Catalog.GetString ("Semi-Automatic");
		this.SemiAutomatic_Checkbox.DrawIndicator = true;
		this.SemiAutomatic_Checkbox.UseUnderline = true;
		this.hbox60.Add (this.SemiAutomatic_Checkbox);
		global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.hbox60 [this.SemiAutomatic_Checkbox]));
		w99.Position = 1;
		this.vbox3.Add (this.hbox60);
		global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox60]));
		w100.Position = 0;
		w100.Expand = false;
		w100.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox61 = new global::Gtk.HBox ();
		this.hbox61.Name = "hbox61";
		this.hbox61.Spacing = 6;
		// Container child hbox61.Gtk.Box+BoxChild
		this.SemiAutomaticBurst_Checkbox = new global::Gtk.CheckButton ();
		this.SemiAutomaticBurst_Checkbox.CanFocus = true;
		this.SemiAutomaticBurst_Checkbox.Name = "SemiAutomaticBurst_Checkbox";
		this.SemiAutomaticBurst_Checkbox.Label = global::Mono.Unix.Catalog.GetString ("Semi-Automatic Burst");
		this.SemiAutomaticBurst_Checkbox.DrawIndicator = true;
		this.SemiAutomaticBurst_Checkbox.UseUnderline = true;
		this.hbox61.Add (this.SemiAutomaticBurst_Checkbox);
		global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.hbox61 [this.SemiAutomaticBurst_Checkbox]));
		w101.Position = 0;
		// Container child hbox61.Gtk.Box+BoxChild
		this.BurstFire_Checkbox = new global::Gtk.CheckButton ();
		this.BurstFire_Checkbox.CanFocus = true;
		this.BurstFire_Checkbox.Name = "BurstFire_Checkbox";
		this.BurstFire_Checkbox.Label = global::Mono.Unix.Catalog.GetString ("Burst Fire");
		this.BurstFire_Checkbox.DrawIndicator = true;
		this.BurstFire_Checkbox.UseUnderline = true;
		this.hbox61.Add (this.BurstFire_Checkbox);
		global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.hbox61 [this.BurstFire_Checkbox]));
		w102.Position = 1;
		this.vbox3.Add (this.hbox61);
		global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox61]));
		w103.Position = 1;
		w103.Expand = false;
		w103.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox62 = new global::Gtk.HBox ();
		this.hbox62.Name = "hbox62";
		this.hbox62.Spacing = 6;
		// Container child hbox62.Gtk.Box+BoxChild
		this.LongBurst_Checkbox = new global::Gtk.CheckButton ();
		this.LongBurst_Checkbox.CanFocus = true;
		this.LongBurst_Checkbox.Name = "LongBurst_Checkbox";
		this.LongBurst_Checkbox.Label = global::Mono.Unix.Catalog.GetString ("Long Burst");
		this.LongBurst_Checkbox.DrawIndicator = true;
		this.LongBurst_Checkbox.UseUnderline = true;
		this.hbox62.Add (this.LongBurst_Checkbox);
		global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.hbox62 [this.LongBurst_Checkbox]));
		w104.Position = 0;
		// Container child hbox62.Gtk.Box+BoxChild
		this.FullAuto_Checkbox = new global::Gtk.CheckButton ();
		this.FullAuto_Checkbox.CanFocus = true;
		this.FullAuto_Checkbox.Name = "FullAuto_Checkbox";
		this.FullAuto_Checkbox.Label = global::Mono.Unix.Catalog.GetString ("Full Auto");
		this.FullAuto_Checkbox.DrawIndicator = true;
		this.FullAuto_Checkbox.UseUnderline = true;
		this.hbox62.Add (this.FullAuto_Checkbox);
		global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.hbox62 [this.FullAuto_Checkbox]));
		w105.Position = 1;
		this.vbox3.Add (this.hbox62);
		global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox62]));
		w106.Position = 2;
		w106.Expand = false;
		w106.Fill = false;
		this.FiringModes_Expander.Add (this.vbox3);
		this.FiringModesExpander_Label = new global::Gtk.Label ();
		this.FiringModesExpander_Label.Name = "FiringModesExpander_Label";
		this.FiringModesExpander_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>FiringModes</b>");
		this.FiringModesExpander_Label.UseMarkup = true;
		this.FiringModesExpander_Label.UseUnderline = true;
		this.FiringModes_Expander.LabelWidget = this.FiringModesExpander_Label;
		this.vbox7.Add (this.FiringModes_Expander);
		global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.FiringModes_Expander]));
		w108.Position = 8;
		w108.Expand = false;
		w108.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.RangedSkill_Expander = new global::Gtk.Expander (null);
		this.RangedSkill_Expander.CanFocus = true;
		this.RangedSkill_Expander.Name = "RangedSkill_Expander";
		this.RangedSkill_Expander.Expanded = true;
		// Container child RangedSkill_Expander.Gtk.Container+ContainerChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox21 = new global::Gtk.HBox ();
		this.hbox21.Name = "hbox21";
		this.hbox21.Spacing = 6;
		// Container child hbox21.Gtk.Box+BoxChild
		this.Archery_Radio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Archery"));
		this.Archery_Radio.CanFocus = true;
		this.Archery_Radio.Name = "Archery_Radio";
		this.Archery_Radio.Active = true;
		this.Archery_Radio.DrawIndicator = true;
		this.Archery_Radio.UseUnderline = true;
		this.Archery_Radio.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.hbox21.Add (this.Archery_Radio);
		global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.Archery_Radio]));
		w109.Position = 0;
		// Container child hbox21.Gtk.Box+BoxChild
		this.Automatics_Radio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Automatics"));
		this.Automatics_Radio.CanFocus = true;
		this.Automatics_Radio.Name = "Automatics_Radio";
		this.Automatics_Radio.DrawIndicator = true;
		this.Automatics_Radio.UseUnderline = true;
		this.Automatics_Radio.Group = this.Archery_Radio.Group;
		this.hbox21.Add (this.Automatics_Radio);
		global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.Automatics_Radio]));
		w110.Position = 1;
		this.vbox6.Add (this.hbox21);
		global::Gtk.Box.BoxChild w111 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox21]));
		w111.Position = 0;
		w111.Expand = false;
		w111.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox22 = new global::Gtk.HBox ();
		this.hbox22.Name = "hbox22";
		this.hbox22.Spacing = 6;
		// Container child hbox22.Gtk.Box+BoxChild
		this.HeavyWeapons_Radio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Heavy Weapons"));
		this.HeavyWeapons_Radio.CanFocus = true;
		this.HeavyWeapons_Radio.Name = "HeavyWeapons_Radio";
		this.HeavyWeapons_Radio.DrawIndicator = true;
		this.HeavyWeapons_Radio.UseUnderline = true;
		this.HeavyWeapons_Radio.Group = this.Archery_Radio.Group;
		this.hbox22.Add (this.HeavyWeapons_Radio);
		global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.HeavyWeapons_Radio]));
		w112.Position = 0;
		// Container child hbox22.Gtk.Box+BoxChild
		this.Longarms_Radio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Longarms"));
		this.Longarms_Radio.CanFocus = true;
		this.Longarms_Radio.Name = "Longarms_Radio";
		this.Longarms_Radio.DrawIndicator = true;
		this.Longarms_Radio.UseUnderline = true;
		this.Longarms_Radio.Group = this.Archery_Radio.Group;
		this.hbox22.Add (this.Longarms_Radio);
		global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.Longarms_Radio]));
		w113.Position = 1;
		this.vbox6.Add (this.hbox22);
		global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox22]));
		w114.Position = 1;
		w114.Expand = false;
		w114.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox23 = new global::Gtk.HBox ();
		this.hbox23.Name = "hbox23";
		this.hbox23.Spacing = 6;
		// Container child hbox23.Gtk.Box+BoxChild
		this.ThrowingWeapons_Radio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Throwing Weapons"));
		this.ThrowingWeapons_Radio.CanFocus = true;
		this.ThrowingWeapons_Radio.Name = "ThrowingWeapons_Radio";
		this.ThrowingWeapons_Radio.DrawIndicator = true;
		this.ThrowingWeapons_Radio.UseUnderline = true;
		this.ThrowingWeapons_Radio.Group = this.Archery_Radio.Group;
		this.hbox23.Add (this.ThrowingWeapons_Radio);
		global::Gtk.Box.BoxChild w115 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.ThrowingWeapons_Radio]));
		w115.Position = 0;
		// Container child hbox23.Gtk.Box+BoxChild
		this.Pistols_Radio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Pistols"));
		this.Pistols_Radio.CanFocus = true;
		this.Pistols_Radio.Name = "Pistols_Radio";
		this.Pistols_Radio.DrawIndicator = true;
		this.Pistols_Radio.UseUnderline = true;
		this.Pistols_Radio.Group = this.Archery_Radio.Group;
		this.hbox23.Add (this.Pistols_Radio);
		global::Gtk.Box.BoxChild w116 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.Pistols_Radio]));
		w116.Position = 1;
		this.vbox6.Add (this.hbox23);
		global::Gtk.Box.BoxChild w117 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox23]));
		w117.PackType = ((global::Gtk.PackType)(1));
		w117.Position = 2;
		w117.Expand = false;
		w117.Fill = false;
		this.RangedSkill_Expander.Add (this.vbox6);
		this.RangedSkillExpander_Label = new global::Gtk.Label ();
		this.RangedSkillExpander_Label.Name = "RangedSkillExpander_Label";
		this.RangedSkillExpander_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Related Skill</b>");
		this.RangedSkillExpander_Label.UseMarkup = true;
		this.RangedSkillExpander_Label.UseUnderline = true;
		this.RangedSkill_Expander.LabelWidget = this.RangedSkillExpander_Label;
		this.vbox7.Add (this.RangedSkill_Expander);
		global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.RangedSkill_Expander]));
		w119.Position = 9;
		w119.Expand = false;
		w119.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.ImportRanged_Button = new global::Gtk.Button ();
		this.ImportRanged_Button.CanFocus = true;
		this.ImportRanged_Button.Name = "ImportRanged_Button";
		this.ImportRanged_Button.UseUnderline = true;
		this.ImportRanged_Button.Label = global::Mono.Unix.Catalog.GetString ("Import Ranged Weapon Stats");
		this.vbox7.Add (this.ImportRanged_Button);
		global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.ImportRanged_Button]));
		w120.Position = 10;
		w120.Expand = false;
		w120.Fill = false;
		this.GtkAlignment4.Add (this.vbox7);
		this.RangedWeapon_Frame.Add (this.GtkAlignment4);
		this.Weapons_Vbox.Add (this.RangedWeapon_Frame);
		global::Gtk.Box.BoxChild w123 = ((global::Gtk.Box.BoxChild)(this.Weapons_Vbox [this.RangedWeapon_Frame]));
		w123.Position = 0;
		w123.Expand = false;
		w123.Fill = false;
		// Container child Weapons_Vbox.Gtk.Box+BoxChild
		this.hseparator4 = new global::Gtk.HSeparator ();
		this.hseparator4.Name = "hseparator4";
		this.Weapons_Vbox.Add (this.hseparator4);
		global::Gtk.Box.BoxChild w124 = ((global::Gtk.Box.BoxChild)(this.Weapons_Vbox [this.hseparator4]));
		w124.Position = 1;
		w124.Expand = false;
		w124.Fill = false;
		// Container child Weapons_Vbox.Gtk.Box+BoxChild
		this.MeleeWeapon_Frame = new global::Gtk.Frame ();
		this.MeleeWeapon_Frame.Name = "MeleeWeapon_Frame";
		this.MeleeWeapon_Frame.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child MeleeWeapon_Frame.Gtk.Container+ContainerChild
		this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment5.Name = "GtkAlignment5";
		this.GtkAlignment5.LeftPadding = ((uint)(12));
		// Container child GtkAlignment5.Gtk.Container+ContainerChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.MeleeWeapon_Label = new global::Gtk.Label ();
		this.MeleeWeapon_Label.Name = "MeleeWeapon_Label";
		this.MeleeWeapon_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Melee Weapon</b>");
		this.MeleeWeapon_Label.UseMarkup = true;
		this.vbox8.Add (this.MeleeWeapon_Label);
		global::Gtk.Box.BoxChild w125 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.MeleeWeapon_Label]));
		w125.Position = 0;
		w125.Expand = false;
		w125.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.MeleeWeaponName_Label = new global::Gtk.Label ();
		this.MeleeWeaponName_Label.Name = "MeleeWeaponName_Label";
		this.MeleeWeaponName_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
		this.hbox9.Add (this.MeleeWeaponName_Label);
		global::Gtk.Box.BoxChild w126 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.MeleeWeaponName_Label]));
		w126.Position = 0;
		w126.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.MeleeWeaponName_Textbox = new global::Gtk.Entry ();
		this.MeleeWeaponName_Textbox.CanFocus = true;
		this.MeleeWeaponName_Textbox.Name = "MeleeWeaponName_Textbox";
		this.MeleeWeaponName_Textbox.IsEditable = true;
		this.MeleeWeaponName_Textbox.InvisibleChar = '●';
		this.hbox9.Add (this.MeleeWeaponName_Textbox);
		global::Gtk.Box.BoxChild w127 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.MeleeWeaponName_Textbox]));
		w127.Position = 1;
		w127.Expand = false;
		this.vbox8.Add (this.hbox9);
		global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox9]));
		w128.Position = 1;
		w128.Expand = false;
		w128.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox63 = new global::Gtk.HBox ();
		this.hbox63.Name = "hbox63";
		this.hbox63.Spacing = 6;
		// Container child hbox63.Gtk.Box+BoxChild
		this.MeleeDamage_Label = new global::Gtk.Label ();
		this.MeleeDamage_Label.Name = "MeleeDamage_Label";
		this.MeleeDamage_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Damage");
		this.hbox63.Add (this.MeleeDamage_Label);
		global::Gtk.Box.BoxChild w129 = ((global::Gtk.Box.BoxChild)(this.hbox63 [this.MeleeDamage_Label]));
		w129.Position = 0;
		w129.Fill = false;
		// Container child hbox63.Gtk.Box+BoxChild
		this.MeleeDamage_Textbox = new global::Gtk.Entry ();
		this.MeleeDamage_Textbox.CanFocus = true;
		this.MeleeDamage_Textbox.Name = "MeleeDamage_Textbox";
		this.MeleeDamage_Textbox.IsEditable = true;
		this.MeleeDamage_Textbox.InvisibleChar = '●';
		this.hbox63.Add (this.MeleeDamage_Textbox);
		global::Gtk.Box.BoxChild w130 = ((global::Gtk.Box.BoxChild)(this.hbox63 [this.MeleeDamage_Textbox]));
		w130.Position = 1;
		w130.Expand = false;
		this.vbox8.Add (this.hbox63);
		global::Gtk.Box.BoxChild w131 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox63]));
		w131.Position = 2;
		w131.Expand = false;
		w131.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox64 = new global::Gtk.HBox ();
		this.hbox64.Name = "hbox64";
		this.hbox64.Spacing = 6;
		// Container child hbox64.Gtk.Box+BoxChild
		this.MeleeDamageType_Label = new global::Gtk.Label ();
		this.MeleeDamageType_Label.Name = "MeleeDamageType_Label";
		this.MeleeDamageType_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Type");
		this.hbox64.Add (this.MeleeDamageType_Label);
		global::Gtk.Box.BoxChild w132 = ((global::Gtk.Box.BoxChild)(this.hbox64 [this.MeleeDamageType_Label]));
		w132.Position = 0;
		w132.Fill = false;
		// Container child hbox64.Gtk.Box+BoxChild
		this.MeleePhysicalDamage_Radio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Physical"));
		this.MeleePhysicalDamage_Radio.CanFocus = true;
		this.MeleePhysicalDamage_Radio.Name = "MeleePhysicalDamage_Radio";
		this.MeleePhysicalDamage_Radio.Active = true;
		this.MeleePhysicalDamage_Radio.DrawIndicator = true;
		this.MeleePhysicalDamage_Radio.UseUnderline = true;
		this.MeleePhysicalDamage_Radio.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.hbox64.Add (this.MeleePhysicalDamage_Radio);
		global::Gtk.Box.BoxChild w133 = ((global::Gtk.Box.BoxChild)(this.hbox64 [this.MeleePhysicalDamage_Radio]));
		w133.Position = 1;
		w133.Expand = false;
		// Container child hbox64.Gtk.Box+BoxChild
		this.MeleeStunDamage_Radio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Stun"));
		this.MeleeStunDamage_Radio.CanFocus = true;
		this.MeleeStunDamage_Radio.Name = "MeleeStunDamage_Radio";
		this.MeleeStunDamage_Radio.DrawIndicator = true;
		this.MeleeStunDamage_Radio.UseUnderline = true;
		this.MeleeStunDamage_Radio.Group = this.MeleePhysicalDamage_Radio.Group;
		this.hbox64.Add (this.MeleeStunDamage_Radio);
		global::Gtk.Box.BoxChild w134 = ((global::Gtk.Box.BoxChild)(this.hbox64 [this.MeleeStunDamage_Radio]));
		w134.Position = 2;
		w134.Expand = false;
		this.vbox8.Add (this.hbox64);
		global::Gtk.Box.BoxChild w135 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox64]));
		w135.Position = 3;
		w135.Expand = false;
		w135.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox65 = new global::Gtk.HBox ();
		this.hbox65.Name = "hbox65";
		this.hbox65.Spacing = 6;
		// Container child hbox65.Gtk.Box+BoxChild
		this.MeleeAP_Label = new global::Gtk.Label ();
		this.MeleeAP_Label.Name = "MeleeAP_Label";
		this.MeleeAP_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("AP");
		this.hbox65.Add (this.MeleeAP_Label);
		global::Gtk.Box.BoxChild w136 = ((global::Gtk.Box.BoxChild)(this.hbox65 [this.MeleeAP_Label]));
		w136.Position = 0;
		w136.Fill = false;
		// Container child hbox65.Gtk.Box+BoxChild
		this.MeleeAP_Textbox = new global::Gtk.Entry ();
		this.MeleeAP_Textbox.CanFocus = true;
		this.MeleeAP_Textbox.Name = "MeleeAP_Textbox";
		this.MeleeAP_Textbox.IsEditable = true;
		this.MeleeAP_Textbox.InvisibleChar = '●';
		this.hbox65.Add (this.MeleeAP_Textbox);
		global::Gtk.Box.BoxChild w137 = ((global::Gtk.Box.BoxChild)(this.hbox65 [this.MeleeAP_Textbox]));
		w137.Position = 1;
		w137.Expand = false;
		this.vbox8.Add (this.hbox65);
		global::Gtk.Box.BoxChild w138 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox65]));
		w138.Position = 4;
		w138.Expand = false;
		w138.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox28 = new global::Gtk.HBox ();
		this.hbox28.Name = "hbox28";
		this.hbox28.Spacing = 6;
		// Container child hbox28.Gtk.Box+BoxChild
		this.MeleeAccuracy_Label = new global::Gtk.Label ();
		this.MeleeAccuracy_Label.Name = "MeleeAccuracy_Label";
		this.MeleeAccuracy_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Accuracy");
		this.hbox28.Add (this.MeleeAccuracy_Label);
		global::Gtk.Box.BoxChild w139 = ((global::Gtk.Box.BoxChild)(this.hbox28 [this.MeleeAccuracy_Label]));
		w139.Position = 0;
		w139.Fill = false;
		// Container child hbox28.Gtk.Box+BoxChild
		this.MeleeAccuracy_Textbox = new global::Gtk.Entry ();
		this.MeleeAccuracy_Textbox.CanFocus = true;
		this.MeleeAccuracy_Textbox.Name = "MeleeAccuracy_Textbox";
		this.MeleeAccuracy_Textbox.IsEditable = true;
		this.MeleeAccuracy_Textbox.InvisibleChar = '●';
		this.hbox28.Add (this.MeleeAccuracy_Textbox);
		global::Gtk.Box.BoxChild w140 = ((global::Gtk.Box.BoxChild)(this.hbox28 [this.MeleeAccuracy_Textbox]));
		w140.Position = 1;
		w140.Expand = false;
		this.vbox8.Add (this.hbox28);
		global::Gtk.Box.BoxChild w141 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox28]));
		w141.Position = 5;
		w141.Expand = false;
		w141.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.MeleeSkill_Expander = new global::Gtk.Expander (null);
		this.MeleeSkill_Expander.CanFocus = true;
		this.MeleeSkill_Expander.Name = "MeleeSkill_Expander";
		this.MeleeSkill_Expander.Expanded = true;
		// Container child MeleeSkill_Expander.Gtk.Container+ContainerChild
		this.vbox10 = new global::Gtk.VBox ();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.hbox25 = new global::Gtk.HBox ();
		this.hbox25.Name = "hbox25";
		this.hbox25.Spacing = 6;
		// Container child hbox25.Gtk.Box+BoxChild
		this.Blades_Radio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Blades"));
		this.Blades_Radio.CanFocus = true;
		this.Blades_Radio.Name = "Blades_Radio";
		this.Blades_Radio.Active = true;
		this.Blades_Radio.DrawIndicator = true;
		this.Blades_Radio.UseUnderline = true;
		this.Blades_Radio.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.hbox25.Add (this.Blades_Radio);
		global::Gtk.Box.BoxChild w142 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.Blades_Radio]));
		w142.Position = 0;
		// Container child hbox25.Gtk.Box+BoxChild
		this.Clubs_Radio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Clubs"));
		this.Clubs_Radio.CanFocus = true;
		this.Clubs_Radio.Name = "Clubs_Radio";
		this.Clubs_Radio.DrawIndicator = true;
		this.Clubs_Radio.UseUnderline = true;
		this.Clubs_Radio.Group = this.Blades_Radio.Group;
		this.hbox25.Add (this.Clubs_Radio);
		global::Gtk.Box.BoxChild w143 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.Clubs_Radio]));
		w143.Position = 1;
		this.vbox10.Add (this.hbox25);
		global::Gtk.Box.BoxChild w144 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox25]));
		w144.Position = 0;
		w144.Expand = false;
		w144.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.hbox24 = new global::Gtk.HBox ();
		this.hbox24.Name = "hbox24";
		this.hbox24.Spacing = 6;
		// Container child hbox24.Gtk.Box+BoxChild
		this.Unarmed_Radio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Unarmed"));
		this.Unarmed_Radio.CanFocus = true;
		this.Unarmed_Radio.Name = "Unarmed_Radio";
		this.Unarmed_Radio.DrawIndicator = true;
		this.Unarmed_Radio.UseUnderline = true;
		this.Unarmed_Radio.Group = this.Blades_Radio.Group;
		this.hbox24.Add (this.Unarmed_Radio);
		global::Gtk.Box.BoxChild w145 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.Unarmed_Radio]));
		w145.Position = 0;
		this.vbox10.Add (this.hbox24);
		global::Gtk.Box.BoxChild w146 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox24]));
		w146.Position = 1;
		w146.Expand = false;
		w146.Fill = false;
		this.MeleeSkill_Expander.Add (this.vbox10);
		this.MeleeSkillExpander_Label = new global::Gtk.Label ();
		this.MeleeSkillExpander_Label.Name = "MeleeSkillExpander_Label";
		this.MeleeSkillExpander_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Related Skill</b>");
		this.MeleeSkillExpander_Label.UseMarkup = true;
		this.MeleeSkillExpander_Label.UseUnderline = true;
		this.MeleeSkill_Expander.LabelWidget = this.MeleeSkillExpander_Label;
		this.vbox8.Add (this.MeleeSkill_Expander);
		global::Gtk.Box.BoxChild w148 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.MeleeSkill_Expander]));
		w148.Position = 6;
		w148.Expand = false;
		w148.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.ImportWeapons_Button = new global::Gtk.Button ();
		this.ImportWeapons_Button.CanFocus = true;
		this.ImportWeapons_Button.Name = "ImportWeapons_Button";
		this.ImportWeapons_Button.UseUnderline = true;
		this.ImportWeapons_Button.Label = global::Mono.Unix.Catalog.GetString ("Import Melee Weapons Stats");
		this.vbox8.Add (this.ImportWeapons_Button);
		global::Gtk.Box.BoxChild w149 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.ImportWeapons_Button]));
		w149.Position = 7;
		w149.Expand = false;
		w149.Fill = false;
		this.GtkAlignment5.Add (this.vbox8);
		this.MeleeWeapon_Frame.Add (this.GtkAlignment5);
		this.Weapons_Vbox.Add (this.MeleeWeapon_Frame);
		global::Gtk.Box.BoxChild w152 = ((global::Gtk.Box.BoxChild)(this.Weapons_Vbox [this.MeleeWeapon_Frame]));
		w152.Position = 2;
		w152.Expand = false;
		w152.Fill = false;
		this.GtkAlignment.Add (this.Weapons_Vbox);
		this.Weapons_Frame.Add (this.GtkAlignment);
		this.WeaponsPane_Label = new global::Gtk.Label ();
		this.WeaponsPane_Label.Name = "WeaponsPane_Label";
		this.WeaponsPane_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Weapons</b>");
		this.WeaponsPane_Label.UseMarkup = true;
		this.Weapons_Frame.LabelWidget = this.WeaponsPane_Label;
		this.Character_Pane.Add (this.Weapons_Frame);
		global::Gtk.Box.BoxChild w155 = ((global::Gtk.Box.BoxChild)(this.Character_Pane [this.Weapons_Frame]));
		w155.Position = 1;
		w155.Expand = false;
		w155.Fill = false;
		this.vbox5.Add (this.Character_Pane);
		global::Gtk.Box.BoxChild w156 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.Character_Pane]));
		w156.Position = 0;
		w156.Expand = false;
		w156.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator ();
		this.hseparator3.Name = "hseparator3";
		this.vbox5.Add (this.hseparator3);
		global::Gtk.Box.BoxChild w157 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hseparator3]));
		w157.Position = 1;
		w157.Expand = false;
		w157.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.SubmitCharacter_Button = new global::Gtk.Button ();
		this.SubmitCharacter_Button.CanFocus = true;
		this.SubmitCharacter_Button.Name = "SubmitCharacter_Button";
		this.SubmitCharacter_Button.UseUnderline = true;
		this.SubmitCharacter_Button.Label = global::Mono.Unix.Catalog.GetString ("Submit Character");
		this.vbox5.Add (this.SubmitCharacter_Button);
		global::Gtk.Box.BoxChild w158 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.SubmitCharacter_Button]));
		w158.Position = 2;
		w158.Expand = false;
		w158.Fill = false;
		this.Add (this.vbox5);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 588;
		this.DefaultHeight = 852;
		this.Show ();
		this.ImportAttributeSection_Button.Clicked += new global::System.EventHandler (this.AttributeImport_Click);
		this.ImportRanged_Button.Clicked += new global::System.EventHandler (this.RangedWeaponImport_Click);
		this.ImportWeapons_Button.Clicked += new global::System.EventHandler (this.MeleeWeaponImport_Click);
		this.SubmitCharacter_Button.Clicked += new global::System.EventHandler (this.SubmitCharacter_Click);
	}
}
