
// This file has been generated by the GUI designer. Do not modify.
namespace ShadowrunGui
{
	public partial class MessageWindow
	{
		private global::Gtk.VBox vbox7;
		private global::Gtk.Label Message_Label;
		private global::Gtk.HSeparator hseparator4;
		private global::Gtk.Button Ok_Button;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ShadowrunGui.MessageWindow
			this.Name = "ShadowrunGui.MessageWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MessageWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ShadowrunGui.MessageWindow.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.Message_Label = new global::Gtk.Label ();
			this.Message_Label.Name = "Message_Label";
			this.Message_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Somthing");
			this.vbox7.Add (this.Message_Label);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.Message_Label]));
			w1.Position = 0;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator ();
			this.hseparator4.Name = "hseparator4";
			this.vbox7.Add (this.hseparator4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hseparator4]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.Ok_Button = new global::Gtk.Button ();
			this.Ok_Button.CanFocus = true;
			this.Ok_Button.Name = "Ok_Button";
			this.Ok_Button.UseUnderline = true;
			this.Ok_Button.Label = global::Mono.Unix.Catalog.GetString ("Ok");
			this.vbox7.Add (this.Ok_Button);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.Ok_Button]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.vbox7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 312;
			this.DefaultHeight = 132;
			this.Show ();
			this.Ok_Button.Clicked += new global::System.EventHandler (this.Ok_Click);
		}
	}
}
