
// This file has been generated by the GUI designer. Do not modify.
namespace ShadowrunGui
{
	public partial class InputWindow
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label Message_Label;
		private global::Gtk.Entry Input_Textbox;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.Button Submit_Button;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ShadowrunGui.InputWindow
			this.Name = "ShadowrunGui.InputWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("InputWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ShadowrunGui.InputWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.Message_Label = new global::Gtk.Label ();
			this.Message_Label.Name = "Message_Label";
			this.Message_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Message");
			this.hbox3.Add (this.Message_Label);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.Message_Label]));
			w1.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.Input_Textbox = new global::Gtk.Entry ();
			this.Input_Textbox.CanFocus = true;
			this.Input_Textbox.Name = "Input_Textbox";
			this.Input_Textbox.IsEditable = true;
			this.Input_Textbox.InvisibleChar = '●';
			this.hbox3.Add (this.Input_Textbox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.Input_Textbox]));
			w2.Position = 1;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w3.Position = 0;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox2.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator2]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.Submit_Button = new global::Gtk.Button ();
			this.Submit_Button.CanFocus = true;
			this.Submit_Button.Name = "Submit_Button";
			this.Submit_Button.UseUnderline = true;
			this.Submit_Button.Label = global::Mono.Unix.Catalog.GetString ("Submit");
			this.vbox2.Add (this.Submit_Button);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.Submit_Button]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 129;
			this.Show ();
			this.Submit_Button.Clicked += new global::System.EventHandler (this.Submit_Click);
		}
	}
}
