
// This file has been generated by the GUI designer. Do not modify.
namespace ShadowrunGui
{
	public partial class ShadowrunWirelessTools
	{
		private global::Gtk.Notebook ShadowrunWirelessTools_Notebook;
		private global::ShadowrunGui.CharacterPageWidget characterpagewidget1;
		private global::Gtk.Label CharacterImportTab_Label;
		private global::ShadowrunGui.CombatPageWidget combatpagewidget1;
		private global::Gtk.Label CombatTab_Label;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ShadowrunGui.ShadowrunWirelessTools
			this.Name = "ShadowrunGui.ShadowrunWirelessTools";
			this.Title = global::Mono.Unix.Catalog.GetString ("ShadowrunWirelessTools");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ShadowrunGui.ShadowrunWirelessTools.Gtk.Container+ContainerChild
			this.ShadowrunWirelessTools_Notebook = new global::Gtk.Notebook ();
			this.ShadowrunWirelessTools_Notebook.CanFocus = true;
			this.ShadowrunWirelessTools_Notebook.Name = "ShadowrunWirelessTools_Notebook";
			this.ShadowrunWirelessTools_Notebook.CurrentPage = 0;
			// Container child ShadowrunWirelessTools_Notebook.Gtk.Notebook+NotebookChild
			this.characterpagewidget1 = new global::ShadowrunGui.CharacterPageWidget ();
			this.characterpagewidget1.Events = ((global::Gdk.EventMask)(256));
			this.characterpagewidget1.Name = "characterpagewidget1";
			this.ShadowrunWirelessTools_Notebook.Add (this.characterpagewidget1);
			// Notebook tab
			this.CharacterImportTab_Label = new global::Gtk.Label ();
			this.CharacterImportTab_Label.Name = "CharacterImportTab_Label";
			this.CharacterImportTab_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Character Import");
			this.ShadowrunWirelessTools_Notebook.SetTabLabel (this.characterpagewidget1, this.CharacterImportTab_Label);
			this.CharacterImportTab_Label.ShowAll ();
			// Container child ShadowrunWirelessTools_Notebook.Gtk.Notebook+NotebookChild
			this.combatpagewidget1 = new global::ShadowrunGui.CombatPageWidget ();
			this.combatpagewidget1.Events = ((global::Gdk.EventMask)(256));
			this.combatpagewidget1.Name = "combatpagewidget1";
			this.ShadowrunWirelessTools_Notebook.Add (this.combatpagewidget1);
			global::Gtk.Notebook.NotebookChild w2 = ((global::Gtk.Notebook.NotebookChild)(this.ShadowrunWirelessTools_Notebook [this.combatpagewidget1]));
			w2.Position = 1;
			// Notebook tab
			this.CombatTab_Label = new global::Gtk.Label ();
			this.CombatTab_Label.Name = "CombatTab_Label";
			this.CombatTab_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Combat");
			this.ShadowrunWirelessTools_Notebook.SetTabLabel (this.combatpagewidget1, this.CombatTab_Label);
			this.CombatTab_Label.ShowAll ();
			this.Add (this.ShadowrunWirelessTools_Notebook);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 984;
			this.DefaultHeight = 506;
			this.Show ();
		}
	}
}
