
// This file has been generated by the GUI designer. Do not modify.
namespace ShadowrunGui
{
	public partial class CombatPageWidget
	{
		private global::Gtk.VBox Combat_Box1;
		private global::Gtk.HBox Combat_Box2;
		private global::Gtk.Frame Initiative_Frame1;
		private global::Gtk.Alignment GtkAlignment5;
		private global::Gtk.ScrolledWindow InitiativeTree_ScrolledWindow;
		private global::Gtk.TreeView Initiative_TreeView;
		private global::Gtk.Label InitiativeFrame_Label;
		private global::Gtk.Frame CharacterStatus_Frame;
		private global::Gtk.Alignment GtkAlignment4;
		private global::Gtk.TreeView CharacterStatus_TreeView;
		private global::Gtk.Label CharacterStatus_Label;
		private global::Gtk.VBox Controls_Box;
		private global::Gtk.Frame Status_Frame;
		private global::Gtk.Alignment GtkAlignment3;
		private global::Gtk.VBox vbox10;
		private global::Gtk.Button Reload_Button;
		private global::Gtk.HSeparator hseparator12;
		private global::Gtk.Label Characters_Label;
		private global::Gtk.Frame Initiative_Frame;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Button NewInitiative_Button;
		private global::Gtk.HSeparator hseparator5;
		private global::Gtk.Button NextCharacter_Button;
		private global::Gtk.HSeparator hseparator6;
		private global::Gtk.Button PreviousCharacter_Button;
		private global::Gtk.HSeparator hseparator11;
		private global::Gtk.Button NextPass_Button;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.Button SetCharacterInitiative_Button;
		private global::Gtk.Label Initiative_Label;
		private global::Gtk.Frame Defend_Frame;
		private global::Gtk.Alignment GtkAlignment1;
		private global::Gtk.VBox vbox9;
		private global::Gtk.Button DefendRanged_Button;
		private global::Gtk.HSeparator hseparator7;
		private global::Gtk.Button DefendMelee_Button;
		private global::Gtk.HSeparator hseparator8;
		private global::Gtk.Label Defend_Label;
		private global::Gtk.Frame Attack_Frame;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.VBox vbox8;
		private global::Gtk.Button AttackRanged_Button;
		private global::Gtk.HSeparator hseparator9;
		private global::Gtk.Button AttackMelee_Button;
		private global::Gtk.HSeparator hseparator10;
		private global::Gtk.Label Attack_Label;
		private global::Gtk.Frame LogArea_Frame;
		private global::Gtk.Alignment GtkAlignment6;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView Log_Textview;
		private global::Gtk.Label LogFrame_Label;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ShadowrunGui.CombatPageWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "ShadowrunGui.CombatPageWidget";
			// Container child ShadowrunGui.CombatPageWidget.Gtk.Container+ContainerChild
			this.Combat_Box1 = new global::Gtk.VBox ();
			this.Combat_Box1.Name = "Combat_Box1";
			this.Combat_Box1.Spacing = 6;
			// Container child Combat_Box1.Gtk.Box+BoxChild
			this.Combat_Box2 = new global::Gtk.HBox ();
			this.Combat_Box2.Name = "Combat_Box2";
			this.Combat_Box2.Spacing = 6;
			// Container child Combat_Box2.Gtk.Box+BoxChild
			this.Initiative_Frame1 = new global::Gtk.Frame ();
			this.Initiative_Frame1.Name = "Initiative_Frame1";
			this.Initiative_Frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child Initiative_Frame1.Gtk.Container+ContainerChild
			this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment5.Name = "GtkAlignment5";
			this.GtkAlignment5.LeftPadding = ((uint)(12));
			// Container child GtkAlignment5.Gtk.Container+ContainerChild
			this.InitiativeTree_ScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.InitiativeTree_ScrolledWindow.Name = "InitiativeTree_ScrolledWindow";
			this.InitiativeTree_ScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child InitiativeTree_ScrolledWindow.Gtk.Container+ContainerChild
			this.Initiative_TreeView = new global::Gtk.TreeView ();
			this.Initiative_TreeView.CanFocus = true;
			this.Initiative_TreeView.Name = "Initiative_TreeView";
			this.InitiativeTree_ScrolledWindow.Add (this.Initiative_TreeView);
			this.GtkAlignment5.Add (this.InitiativeTree_ScrolledWindow);
			this.Initiative_Frame1.Add (this.GtkAlignment5);
			this.InitiativeFrame_Label = new global::Gtk.Label ();
			this.InitiativeFrame_Label.Name = "InitiativeFrame_Label";
			this.InitiativeFrame_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Initiative</b>");
			this.InitiativeFrame_Label.UseMarkup = true;
			this.Initiative_Frame1.LabelWidget = this.InitiativeFrame_Label;
			this.Combat_Box2.Add (this.Initiative_Frame1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.Combat_Box2 [this.Initiative_Frame1]));
			w4.Position = 0;
			// Container child Combat_Box2.Gtk.Box+BoxChild
			this.CharacterStatus_Frame = new global::Gtk.Frame ();
			this.CharacterStatus_Frame.WidthRequest = 300;
			this.CharacterStatus_Frame.Name = "CharacterStatus_Frame";
			this.CharacterStatus_Frame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child CharacterStatus_Frame.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.CharacterStatus_TreeView = new global::Gtk.TreeView ();
			this.CharacterStatus_TreeView.CanFocus = true;
			this.CharacterStatus_TreeView.Name = "CharacterStatus_TreeView";
			this.GtkAlignment4.Add (this.CharacterStatus_TreeView);
			this.CharacterStatus_Frame.Add (this.GtkAlignment4);
			this.CharacterStatus_Label = new global::Gtk.Label ();
			this.CharacterStatus_Label.Name = "CharacterStatus_Label";
			this.CharacterStatus_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Character Status</b>");
			this.CharacterStatus_Label.UseMarkup = true;
			this.CharacterStatus_Frame.LabelWidget = this.CharacterStatus_Label;
			this.Combat_Box2.Add (this.CharacterStatus_Frame);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.Combat_Box2 [this.CharacterStatus_Frame]));
			w7.Position = 1;
			w7.Expand = false;
			// Container child Combat_Box2.Gtk.Box+BoxChild
			this.Controls_Box = new global::Gtk.VBox ();
			this.Controls_Box.Name = "Controls_Box";
			this.Controls_Box.Spacing = 6;
			// Container child Controls_Box.Gtk.Box+BoxChild
			this.Status_Frame = new global::Gtk.Frame ();
			this.Status_Frame.Name = "Status_Frame";
			this.Status_Frame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child Status_Frame.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.Reload_Button = new global::Gtk.Button ();
			this.Reload_Button.CanFocus = true;
			this.Reload_Button.Name = "Reload_Button";
			this.Reload_Button.UseUnderline = true;
			this.Reload_Button.Label = global::Mono.Unix.Catalog.GetString ("Reload");
			this.vbox10.Add (this.Reload_Button);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.Reload_Button]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hseparator12 = new global::Gtk.HSeparator ();
			this.hseparator12.Name = "hseparator12";
			this.vbox10.Add (this.hseparator12);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hseparator12]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.GtkAlignment3.Add (this.vbox10);
			this.Status_Frame.Add (this.GtkAlignment3);
			this.Characters_Label = new global::Gtk.Label ();
			this.Characters_Label.Name = "Characters_Label";
			this.Characters_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Characters</b>");
			this.Characters_Label.UseMarkup = true;
			this.Status_Frame.LabelWidget = this.Characters_Label;
			this.Controls_Box.Add (this.Status_Frame);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.Controls_Box [this.Status_Frame]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child Controls_Box.Gtk.Box+BoxChild
			this.Initiative_Frame = new global::Gtk.Frame ();
			this.Initiative_Frame.Name = "Initiative_Frame";
			this.Initiative_Frame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child Initiative_Frame.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.NewInitiative_Button = new global::Gtk.Button ();
			this.NewInitiative_Button.CanFocus = true;
			this.NewInitiative_Button.Name = "NewInitiative_Button";
			this.NewInitiative_Button.UseUnderline = true;
			this.NewInitiative_Button.Label = global::Mono.Unix.Catalog.GetString ("New Initiative");
			this.vbox5.Add (this.NewInitiative_Button);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.NewInitiative_Button]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hseparator5 = new global::Gtk.HSeparator ();
			this.hseparator5.Name = "hseparator5";
			this.vbox5.Add (this.hseparator5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hseparator5]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.NextCharacter_Button = new global::Gtk.Button ();
			this.NextCharacter_Button.CanFocus = true;
			this.NextCharacter_Button.Name = "NextCharacter_Button";
			this.NextCharacter_Button.UseUnderline = true;
			this.NextCharacter_Button.Label = global::Mono.Unix.Catalog.GetString ("Next Character");
			this.vbox5.Add (this.NextCharacter_Button);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.NextCharacter_Button]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hseparator6 = new global::Gtk.HSeparator ();
			this.hseparator6.Name = "hseparator6";
			this.vbox5.Add (this.hseparator6);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hseparator6]));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.PreviousCharacter_Button = new global::Gtk.Button ();
			this.PreviousCharacter_Button.CanFocus = true;
			this.PreviousCharacter_Button.Name = "PreviousCharacter_Button";
			this.PreviousCharacter_Button.UseUnderline = true;
			this.PreviousCharacter_Button.Label = global::Mono.Unix.Catalog.GetString ("Previous Character");
			this.vbox5.Add (this.PreviousCharacter_Button);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.PreviousCharacter_Button]));
			w17.Position = 4;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hseparator11 = new global::Gtk.HSeparator ();
			this.hseparator11.Name = "hseparator11";
			this.vbox5.Add (this.hseparator11);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hseparator11]));
			w18.Position = 5;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.NextPass_Button = new global::Gtk.Button ();
			this.NextPass_Button.CanFocus = true;
			this.NextPass_Button.Name = "NextPass_Button";
			this.NextPass_Button.UseUnderline = true;
			this.NextPass_Button.Label = global::Mono.Unix.Catalog.GetString ("Next Pass");
			this.vbox5.Add (this.NextPass_Button);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.NextPass_Button]));
			w19.Position = 6;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox5.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hseparator1]));
			w20.Position = 7;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.SetCharacterInitiative_Button = new global::Gtk.Button ();
			this.SetCharacterInitiative_Button.CanFocus = true;
			this.SetCharacterInitiative_Button.Name = "SetCharacterInitiative_Button";
			this.SetCharacterInitiative_Button.UseUnderline = true;
			this.SetCharacterInitiative_Button.Label = global::Mono.Unix.Catalog.GetString ("Set Initiative");
			this.vbox5.Add (this.SetCharacterInitiative_Button);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.SetCharacterInitiative_Button]));
			w21.Position = 8;
			w21.Expand = false;
			w21.Fill = false;
			this.GtkAlignment.Add (this.vbox5);
			this.Initiative_Frame.Add (this.GtkAlignment);
			this.Initiative_Label = new global::Gtk.Label ();
			this.Initiative_Label.Name = "Initiative_Label";
			this.Initiative_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Initiative</b>");
			this.Initiative_Label.UseMarkup = true;
			this.Initiative_Frame.LabelWidget = this.Initiative_Label;
			this.Controls_Box.Add (this.Initiative_Frame);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.Controls_Box [this.Initiative_Frame]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child Controls_Box.Gtk.Box+BoxChild
			this.Defend_Frame = new global::Gtk.Frame ();
			this.Defend_Frame.Name = "Defend_Frame";
			this.Defend_Frame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child Defend_Frame.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.DefendRanged_Button = new global::Gtk.Button ();
			this.DefendRanged_Button.CanFocus = true;
			this.DefendRanged_Button.Name = "DefendRanged_Button";
			this.DefendRanged_Button.UseUnderline = true;
			this.DefendRanged_Button.Label = global::Mono.Unix.Catalog.GetString ("Ranged");
			this.vbox9.Add (this.DefendRanged_Button);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.DefendRanged_Button]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hseparator7 = new global::Gtk.HSeparator ();
			this.hseparator7.Name = "hseparator7";
			this.vbox9.Add (this.hseparator7);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hseparator7]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.DefendMelee_Button = new global::Gtk.Button ();
			this.DefendMelee_Button.CanFocus = true;
			this.DefendMelee_Button.Name = "DefendMelee_Button";
			this.DefendMelee_Button.UseUnderline = true;
			this.DefendMelee_Button.Label = global::Mono.Unix.Catalog.GetString ("Melee");
			this.vbox9.Add (this.DefendMelee_Button);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.DefendMelee_Button]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hseparator8 = new global::Gtk.HSeparator ();
			this.hseparator8.Name = "hseparator8";
			this.vbox9.Add (this.hseparator8);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hseparator8]));
			w28.Position = 3;
			w28.Expand = false;
			w28.Fill = false;
			this.GtkAlignment1.Add (this.vbox9);
			this.Defend_Frame.Add (this.GtkAlignment1);
			this.Defend_Label = new global::Gtk.Label ();
			this.Defend_Label.Name = "Defend_Label";
			this.Defend_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Defend-Misc</b>");
			this.Defend_Label.UseMarkup = true;
			this.Defend_Frame.LabelWidget = this.Defend_Label;
			this.Controls_Box.Add (this.Defend_Frame);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.Controls_Box [this.Defend_Frame]));
			w31.Position = 2;
			w31.Expand = false;
			w31.Fill = false;
			// Container child Controls_Box.Gtk.Box+BoxChild
			this.Attack_Frame = new global::Gtk.Frame ();
			this.Attack_Frame.Name = "Attack_Frame";
			this.Attack_Frame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child Attack_Frame.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.AttackRanged_Button = new global::Gtk.Button ();
			this.AttackRanged_Button.CanFocus = true;
			this.AttackRanged_Button.Name = "AttackRanged_Button";
			this.AttackRanged_Button.UseUnderline = true;
			this.AttackRanged_Button.Label = global::Mono.Unix.Catalog.GetString ("Ranged");
			this.vbox8.Add (this.AttackRanged_Button);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.AttackRanged_Button]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hseparator9 = new global::Gtk.HSeparator ();
			this.hseparator9.Name = "hseparator9";
			this.vbox8.Add (this.hseparator9);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hseparator9]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.AttackMelee_Button = new global::Gtk.Button ();
			this.AttackMelee_Button.CanFocus = true;
			this.AttackMelee_Button.Name = "AttackMelee_Button";
			this.AttackMelee_Button.UseUnderline = true;
			this.AttackMelee_Button.Label = global::Mono.Unix.Catalog.GetString ("Melee");
			this.vbox8.Add (this.AttackMelee_Button);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.AttackMelee_Button]));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hseparator10 = new global::Gtk.HSeparator ();
			this.hseparator10.Name = "hseparator10";
			this.vbox8.Add (this.hseparator10);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hseparator10]));
			w35.Position = 3;
			w35.Expand = false;
			w35.Fill = false;
			this.GtkAlignment2.Add (this.vbox8);
			this.Attack_Frame.Add (this.GtkAlignment2);
			this.Attack_Label = new global::Gtk.Label ();
			this.Attack_Label.Name = "Attack_Label";
			this.Attack_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Attack</b>");
			this.Attack_Label.UseMarkup = true;
			this.Attack_Frame.LabelWidget = this.Attack_Label;
			this.Controls_Box.Add (this.Attack_Frame);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.Controls_Box [this.Attack_Frame]));
			w38.Position = 3;
			w38.Expand = false;
			w38.Fill = false;
			this.Combat_Box2.Add (this.Controls_Box);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.Combat_Box2 [this.Controls_Box]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			this.Combat_Box1.Add (this.Combat_Box2);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.Combat_Box1 [this.Combat_Box2]));
			w40.Position = 0;
			// Container child Combat_Box1.Gtk.Box+BoxChild
			this.LogArea_Frame = new global::Gtk.Frame ();
			this.LogArea_Frame.Name = "LogArea_Frame";
			this.LogArea_Frame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child LogArea_Frame.Gtk.Container+ContainerChild
			this.GtkAlignment6 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment6.Name = "GtkAlignment6";
			this.GtkAlignment6.LeftPadding = ((uint)(12));
			// Container child GtkAlignment6.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.Log_Textview = new global::Gtk.TextView ();
			this.Log_Textview.CanFocus = true;
			this.Log_Textview.Name = "Log_Textview";
			this.Log_Textview.Editable = false;
			this.Log_Textview.CursorVisible = false;
			this.GtkScrolledWindow.Add (this.Log_Textview);
			this.GtkAlignment6.Add (this.GtkScrolledWindow);
			this.LogArea_Frame.Add (this.GtkAlignment6);
			this.LogFrame_Label = new global::Gtk.Label ();
			this.LogFrame_Label.Name = "LogFrame_Label";
			this.LogFrame_Label.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Log</b>");
			this.LogFrame_Label.UseMarkup = true;
			this.LogArea_Frame.LabelWidget = this.LogFrame_Label;
			this.Combat_Box1.Add (this.LogArea_Frame);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.Combat_Box1 [this.LogArea_Frame]));
			w44.PackType = ((global::Gtk.PackType)(1));
			w44.Position = 1;
			this.Add (this.Combat_Box1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
